#!/usr/bin/env php
<?php

$paths = [
    '/vendor/autoload.php',
    '/../vendor/autoload.php',
    '/../../autoload.php',
];

foreach ($paths as $path) {
    if (file_exists(__DIR__.$path)) {
        require __DIR__.$path;
        break;
    }
}

use Perform\Cli\Command;
use Perform\Cli\Application;
use Pimple\Container;
use Perform\Cli\PerformCliProvider;

$c = new Container();
$c->register(new PerformCliProvider());

$app = new Application($c);
$app->add(new Command\InitCommand());
$app->add(new Command\ConfigCommand());
$app->add(new Command\SymlinkCommand());
$app->run();
