#!/usr/bin/env php
<?php

include __DIR__.'/vendor/autoload.php';

use Perform\Cli\Command;
use Perform\Cli\Application;
use Pimple\Container;
use Perform\Cli\PerformCliProvider;

$c = new Container();
$c->register(new PerformCliProvider());

$app = new Application($c);
$app->add(new Command\CreateCommand());
$app->add(new Command\InitCommand());
$app->add(new Command\SymlinkCommand());
$app->run();
