.PHONY: vendor

all: install

install:
	composer install
	npm install --no-progress
	bower install
	gulp sass

web_user:
	sudo chown -R www-data:www-data var/
	sudo chown -R www-data:www-data web/uploads/

cli_user:
	sudo chown -R glynn var/
	sudo chown -R glynn web/uploads/

deploy_staging:
	make cli_user
	./bin/console cache:clear --env=staging
	./bin/console doctrine:schema:update --env=staging --force --dump-sql --complete
	make web_user

deploy_prod:
	make cli_user
	./bin/console cache:clear --env=prod
	make web_user

vendor:
	(cd vendor/glynnforrest/perform-bundles/src/BaseBundle && npm install --no-progress)
	(cd vendor/glynnforrest/perform-bundles/src/BaseBundle && bower install)
	(cd vendor/glynnforrest/perform-bundles/src/BaseBundle && grunt sass)
	(cd vendor/glynnforrest/perform-bundles/src/MediaBundle && bower install)

symlink:
	rm -rf vendor/glynnforrest/perform-bundles
	mkdir -p vendor/glynnforrest
	ln -s ~/code/projects/perform-bundles/ vendor/glynnforrest/perform-bundles

remove_symlink:
	rm -f vendor/glynnforrest/perform-bundles
