.PHONY: vendor

all: install

install:
	composer install
	npm install --no-progress
	gulp sass

web_user:
	sudo chown -R www-data:www-data var/

cli_user:
	sudo chown -R glynn var/

deploy_staging:
	make cli_user
	./bin/console cache:clear --env=staging
	./bin/console doctrine:schema:update --env=staging --force --dump-sql --complete
	make web_user

deploy_prod:
	make cli_user
	./bin/console cache:clear --env=prod
	make web_user

vendor:
	(cd vendor/glynnforrest/admin-bundles/src/Base && npm install --no-progress)
	(cd vendor/glynnforrest/admin-bundles/src/Base && bower install)
	(cd vendor/glynnforrest/admin-bundles/src/Base && grunt sass)
	(cd vendor/glynnforrest/admin-bundles/src/MediaBundle && bower install)

symlink:
	rm -rf vendor/glynnforrest/admin-bundles
	mkdir -p vendor/glynnforrest
	ln -s ~/code/projects/admin-bundles/ vendor/glynnforrest/admin-bundles

remove_symlink:
	rm -f vendor/glynnforrest/admin-bundles
