.PHONY: vendor

all: install

install:
	composer install
	npm install --no-progress
	bower install
	gulp sass

web_user:
	sudo chown -R www-data:www-data var/
	sudo chown -R www-data:www-data web/uploads/

cli_user:
	sudo chown -R glynn var/
	sudo chown -R glynn web/uploads/

deploy:
	make cli_user
	make install
	rm -r var/cache/
	./bin/console cache:clear --env=prod
	./bin/console doctrine:migrations:migrate --env=prod --no-interaction
	./bin/console perform:install --env=prod
	./bin/console assets:install --env=prod --symlink
	make web_user
